// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import models "microgo/models"

// IPriceRepository is an autogenerated mock type for the IPriceRepository type
type IPriceRepository struct {
	mock.Mock
}

// FindById provides a mock function with given fields: id
func (_m *IPriceRepository) FindById(id string) (*models.HotelPrice, error) {
	ret := _m.Called(id)

	var r0 *models.HotelPrice
	if rf, ok := ret.Get(0).(func(string) *models.HotelPrice); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.HotelPrice)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: price
func (_m *IPriceRepository) Save(price *models.HotelPrice) (string, error) {
	ret := _m.Called(price)

	var r0 string
	if rf, ok := ret.Get(0).(func(*models.HotelPrice) string); ok {
		r0 = rf(price)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.HotelPrice) error); ok {
		r1 = rf(price)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
